name: Update DB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  deploy-machine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-gnutls-dev libgnutls28-dev

      - name: Install python dependencies
        run: |
          pip3 install --upgrade wheel
          pip3 install -r requirements.txt
          pip3 install -r requirements_dev.txt
          
      - name: Execute update
        run: |
          python3 nut.py -U --import-region US --language en

      - name: Update Release
        run: |
          gh release upload 1.0.0 titledb/titles.json --clobber
          python3 convert.py
          gh release upload 1.0.0 titles.db --clobber || true
          gh release upload 1.0.0 titleasmeta.tfl --clobber || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
